name: AB Contract Deploy
on: [workflow_dispatch, push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          echo "🟢 开始部署！"
          npm install
          npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}